# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tmsg.proto\x12\x02pb\"r\n\x03Pin\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.pb.ValueType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06halbit\x18\x05 \x01(\x08\x12\x10\n\x08halfloat\x18\x06 \x01(\x01\x12\x0e\n\x06hals32\x18\x07 \x01(\x0f\x12\x0e\n\x06halu32\x18\x08 \x01(\x07\"P\n\tContainer\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.pb.ContainerType\x12\x0c\n\x04note\x18\x02 \x03(\t\x12\x14\n\x03pin\x18\x03 \x03(\x0b\x32\x07.pb.Pin*A\n\tValueType\x12\x0b\n\x07HAL_BIT\x10\x00\x12\r\n\tHAL_FLOAT\x10\x01\x12\x0b\n\x07HAL_S32\x10\x02\x12\x0b\n\x07HAL_U32\x10\x03*9\n\rContainerType\x12\x0c\n\x08MT_TEST1\x10\x00\x12\x0c\n\x08MT_TEST2\x10\x01\x12\x0c\n\x08MT_TEST3\x10\x02\x62\x06proto3')
)

_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='pb.ValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HAL_BIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HAL_FLOAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HAL_S32', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HAL_U32', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=215,
  serialized_end=280,
)
_sym_db.RegisterEnumDescriptor(_VALUETYPE)

ValueType = enum_type_wrapper.EnumTypeWrapper(_VALUETYPE)
_CONTAINERTYPE = _descriptor.EnumDescriptor(
  name='ContainerType',
  full_name='pb.ContainerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MT_TEST1', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MT_TEST2', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MT_TEST3', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=282,
  serialized_end=339,
)
_sym_db.RegisterEnumDescriptor(_CONTAINERTYPE)

ContainerType = enum_type_wrapper.EnumTypeWrapper(_CONTAINERTYPE)
HAL_BIT = 0
HAL_FLOAT = 1
HAL_S32 = 2
HAL_U32 = 3
MT_TEST1 = 0
MT_TEST2 = 1
MT_TEST3 = 2



_PIN = _descriptor.Descriptor(
  name='Pin',
  full_name='pb.Pin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.Pin.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='pb.Pin.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='halbit', full_name='pb.Pin.halbit', index=2,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='halfloat', full_name='pb.Pin.halfloat', index=3,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hals32', full_name='pb.Pin.hals32', index=4,
      number=7, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='halu32', full_name='pb.Pin.halu32', index=5,
      number=8, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=131,
)


_CONTAINER = _descriptor.Descriptor(
  name='Container',
  full_name='pb.Container',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.Container.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='pb.Container.note', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin', full_name='pb.Container.pin', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=213,
)

_PIN.fields_by_name['type'].enum_type = _VALUETYPE
_CONTAINER.fields_by_name['type'].enum_type = _CONTAINERTYPE
_CONTAINER.fields_by_name['pin'].message_type = _PIN
DESCRIPTOR.message_types_by_name['Pin'] = _PIN
DESCRIPTOR.message_types_by_name['Container'] = _CONTAINER
DESCRIPTOR.enum_types_by_name['ValueType'] = _VALUETYPE
DESCRIPTOR.enum_types_by_name['ContainerType'] = _CONTAINERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pin = _reflection.GeneratedProtocolMessageType('Pin', (_message.Message,), dict(
  DESCRIPTOR = _PIN,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:pb.Pin)
  ))
_sym_db.RegisterMessage(Pin)

Container = _reflection.GeneratedProtocolMessageType('Container', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINER,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:pb.Container)
  ))
_sym_db.RegisterMessage(Container)


# @@protoc_insertion_point(module_scope)
